name: SFTP-Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - 
        name: deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: 2222
          ssh_private_key: ${{ secrets.SFTP_PRIV_KEY }}
          sftp_only: true
          local_path: '*'
          remote_path: '/'
          sftpArgs: '-o ConnectTimeout=20'
